/* Copyright (C) 2014, 2015 James E. Stark
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ca.uoguelph.socs.icc.edm.domain.datastore.idgenerator;

import java.security.SecureRandom;
import java.util.HashSet;
import java.util.Set;

import ca.uoguelph.socs.icc.edm.domain.datastore.DataStoreQuery;

/**
 * An <code>IdGenerator</code> which returns unique random ID numbers.  The ID
 * numbers are generated using a 64bit cryptographically secure pseudo random
 * number generation algorithm.  All ID's returned by an instance of this class
 * are cached to ensure that no ID number is returned twice.  The user has the
 * option of specifying a <code>Set</code> of previously used id numbers, which
 * the instance will avoid returning.
 *
 * @author  James E. Stark
 * @version 1.0
 */

public class RandomIdGenerator implements IdGenerator
{
	/**
	 * Implementation of the <code>IdGeneratorImplFatory</code> to create
	 * <code>RamdomIdGenerator</code> instances.
	 */

	private static final class Factory implements IdGeneratorImplFactory
	{
		/**
		 * Create the <code>IdGenerator</code> using the specified
		 * <code>DataStoreQuery</code>.
		 *
		 * @param  query The <code>DataStoreQuery</code>, not null
		 *
		 * @return The <code>IdGenerator</code> instance
		 */

		public IdGenerator create (DataStoreQuery<?> query)
		{
			return new RandomIdGenerator (new HashSet<Long> (query.queryAllIds ()));
		}
	}

	/** The <code>Set</code> of previously used id numbers. */
	private Set<Long> usedids;

	/** The random number generator. */
	private SecureRandom generator;

	/**
	 * Static initializer to register the <code>IdGenerator</code> with the
	 * <code>IdGeneratorFactory</code>.
	 */

	static
	{
		(IdGeneratorFactory.getInstance ()).registerClass (RandomIdGenerator.class, new Factory ());
	}

	/**
	 * Create a new <code>RandomIdGenerator</code>.
	 */

	public RandomIdGenerator ()
	{
		this.usedids = new HashSet<Long> ();
		this.generator = new SecureRandom ();
	}

	/**
	 * Create a new <code>RandomIdGenerator</code>, with a set of previously
	 * used Ids.
	 *
	 * @param  usedids A <code>Set</code> of all of the used ID numbers, not
	 *                 null
	 */

	public RandomIdGenerator (Set<Long> usedids)
	{
		this ();
		this.usedids.addAll (usedids);
	}

	/**
	 * Return the next available id number.  This method uses a random number
	 * generator to get the next ID number which it then returns.
	 *
	 * @return A <code>Long</code> containing the next id number
	 */

	@Override
	public Long nextId ()
	{
		Long result = null;

		do
		{
			result = new Long (this.generator.nextLong ());
		} while (! this.usedids.add (result));

		return result;
	}

	/**
	 * Return the <code>Set</code> of previously used ID numbers.  Includes all
	 * of ID numbers generated by this instance of the
	 * <code>IdGenerator</code>, and previous instances.
	 *
	 * @return The <code>Set</code> of previously used id numbers.
	 */

	public Set<Long> getUsedIds ()
	{
		return new HashSet<Long> (this.usedids);
	}
}
