-- Schema for the private database.  Documentation for the schema is on the
-- wiki.

-- Identifying information for students in the public database.
CREATE TABLE IF NOT EXISTS PARTICIPANT (
	ID SERIAL PRIMARY KEY,
	IDNUMBER INTEGER,
	LOGINID VARCHAR[8] NOT NULL,
	GIVENNAME TEXT NOT NULL,
	SURNAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ENROLLEDIN (
	IDNUMBER INTEGER NOT NULL REFERENCES PARTICIPANT(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	ENROLMENTID INTEGER NOT NULL UNIQUE,
	PRIMARY KEY (IDNUMBER, ENROLMENTID)
);

COMMENT ON TABLE PARTICIPANT IS 'Identifying user data';
COMMENT ON TABLE ENROLLEDIN IS 'User to enrolment mapping';